version: 2.1
jobs:
  build:
    working_directory: ~/kagekiri
    docker:
      - image: circleci/node:10-browsers
        environment:
          CHROME_BIN: '/usr/bin/google-chrome'
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # lint
          name: lint
          command: npm run lint
      - run: # run tests
          name: test
          command: npm test
      - run: # check bundle size
          name: bundlesize
          command: npm run test:bundlesize
